apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    # Replace ACCOUNT_NUMBER with the actual aws account number
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_NUMBER>:role/AmazonEKSLoadBalancerControllerRole